name: lyrebird
description: Visual editor for Application Resource Bundle localization files to be used with the intl package.
version: 0.2.1
homepage:
repository: https://github.com/lyrebird-app/launcher

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  alfred: ^1.0.0+1
  args: ^2.3.1
  path: ^1.8.3

dev_dependencies: 
  lints: ^2.0.1
